### PR TITLE
 concepts(core): ExecutionSpace, MemorySpace and Space concepts for C++20 

### PR DESCRIPTION
**Pull request by romintomasetti**
This title says it all.

### CODE REVIEW

**Comment by maartenarnst** [comment]
Wondering if it should be three different files. Might depend on how we want to develop these files in the future and what we want to put in them. Probably best discussed  live.

**Comment by romintomasetti** [comment]
@maartenarnst I just pushed what I had in mind for the backend specializations.

**Comment by maartenarnst** [comment]
Salut Romin,

C’est tres bien! Ce sera pour demain de regarder plus en details.

A demain,
Maarten

On 20 Jun 2024, at 21:55, Tomasetti Romin ***@***.***> wrote:

﻿

@maartenarnst<https://github.com/maartenarnst> I just pushed what I had in mind for the backend specializations.

**Review by maartenarnst — APPROVED** [review]
🟢 !

**Pull request merged**
